## Written by https://github.com/anthonysecco
# To be used with Shelly Plus RGBW PM and a Ford Transit Van.

# Board Configuration
################################################################################
esphome:
  name: "transit-door-interface"
  friendly_name: "Transit Door Interface"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Connectivity
################################################################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  manual_ip:
#    static_ip: 192.168.1.50
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0
#    dns1: 192.168.1.1
  ap: # Backup Access Point if Wi-Fi is unavailable
    password: "12345678"

captive_portal:

# Core Services
################################################################################
logger:

api:

ota:
  - platform: esphome

status_led:
  pin: GPIO14

# Sensors
################################################################################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO36
      inverted: False
    name: "Driver Door"
    device_class: door
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - logger.log: "Driver Door opened!"
    on_release:
      then:
        - logger.log: "Driver Door closed!"

  - platform: gpio
    pin:
      number: GPIO37
      inverted: False
    name: "Passenger Door"
    device_class: door
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - logger.log: "Passenger Door opened!"
    on_release:
      then:
        - logger.log: "Passenger Door closed!"

  - platform: gpio
    pin:
      number: GPIO38
      inverted: True
    name: "Sliding Door"
    device_class: door
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - logger.log: "Sliding Door opened!"
    on_release:
      then:
        - logger.log: "Sliding Door closed!"

  - platform: gpio
    pin:
      number: GPIO39
      inverted: False
    name: "Cargo Doors"
    device_class: door
    filters:
      - delayed_on_off: 10ms
    on_press:
      then:
        - logger.log: "Cargo Doors opened!"
    on_release:
      then:
        - logger.log: "Cargo Doors closed!"

#Outputs
################################################################################
output:  
  - platform: ledc
    pin: GPIO27
    id: pwm_b # B Output - Unused
    frequency: 19531
  
  - platform: ledc
    pin: GPIO4
    id: pwm_w # W Output - Unused
    frequency: 19531

button:
  - platform: template
    id: lock_button
    name: "Lock Doors"
    on_press:
      - switch.turn_on: output_r

  - platform: template
    id: unlock_button
    name: "Unlock Doors"
    on_press:
      - switch.turn_on: output_g

switch:
  - platform: gpio
    id: output_r # Output R - Momentary Lock Button
    name: Output R
    icon: mdi:car-door-lock
    pin: 25
    restore_mode: ALWAYS_OFF
    internal: True
    on_turn_on: 
      - delay: 500ms
      - switch.turn_off: output_r
      - logger.log: Doors Locked

  - platform: gpio
    id: output_g # Output G - Momentary Unlock Button
    name: Output G
    icon: mdi:car-door-lock-open
    pin: 26
    restore_mode: ALWAYS_OFF
    internal: True
    on_turn_on: 
      - delay: 500ms
      - switch.turn_off: output_g
      - logger.log: Doors Unlocked
